# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import time

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = "FANUC ROS 2 Driver Documentation"
author = "FANUC CORPORATION"
copyright = f"{time.strftime('%Y')}, {author}"
release = ""

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"


# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    "sphinx_rtd_theme",
    "sphinx_copybutton",
    "sphinx_tabs.tabs",
    "sphinx.ext.githubpages",
    "sphinx.ext.todo",
    "sphinx_multiversion",
    "myst_parser",
    "sphinxemoji.sphinxemoji",
]

sphinxemoji_style = "twemoji"

# -- (important!) enable MyST’s substitution syntax -----------
# without this, pipes won’t be recognized for emoji
myst_enable_extensions = [
    "amsmath",
    "attrs_inline",
    "colon_fence",
    "deflist",
    "dollarmath",
    "fieldlist",
    "html_admonition",
    "html_image",
    "replacements",
    "smartquotes",
    "strikethrough",
    "substitution",
    "tasklist",
]

templates_path = ["_templates"]

exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", "README.md", "CONTRIBUTING.md"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"


# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = {".rst": "restructuredtext", ".md": "markdown"}

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = "sphinx_rtd_theme"
html_static_path = ["_static"]

# -- Options for sphinx-multiversion ---------------------------------------

# Whitelist pattern for tags you want to build documentation for
smv_tag_whitelist = r"^v\d+\.\d+\.\d+$"  # Semantic versioning

# Whitelist pattern for branches you want to build documentation for
smv_branch_whitelist = r"^main$"

# Whitelist pattern for remotes you want to build documentation for
smv_remote_whitelist = r"^origin$"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

html_context = {
    # Add 'Edit on Github' link instead of 'View page source'
    "display_github": True,
    "github_user": "FANUC-CORPORATION",
    "github_repo": "fanuc_driver_doc",
    "github_version": "main/",
    "conf_py_path": "/",
    "source_suffix": source_suffix,
}

html_logo = "_static/images/fanuc_logo.png"

html_favicon = "_static/images/favicon.ico"

html_css_files = ["css/custom.css"]


def setup(app):
    app.add_css_file("css/custom.css")
